<?php

/**
 * BaseAppUserRegisteredCompanies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $app_user_id
 * @property integer $registered_companies_id
 * @property boolean $notified
 * @property AppUser $AppUser
 * @property RegisteredCompanies $RegisteredCompanies
 * 
 * @method integer                    getId()                      Returns the current record's "id" value
 * @method integer                    getAppUserId()               Returns the current record's "app_user_id" value
 * @method integer                    getRegisteredCompaniesId()   Returns the current record's "registered_companies_id" value
 * @method boolean                    getNotified()                Returns the current record's "notified" value
 * @method AppUser                    getAppUser()                 Returns the current record's "AppUser" value
 * @method RegisteredCompanies        getRegisteredCompanies()     Returns the current record's "RegisteredCompanies" value
 * @method AppUserRegisteredCompanies setId()                      Sets the current record's "id" value
 * @method AppUserRegisteredCompanies setAppUserId()               Sets the current record's "app_user_id" value
 * @method AppUserRegisteredCompanies setRegisteredCompaniesId()   Sets the current record's "registered_companies_id" value
 * @method AppUserRegisteredCompanies setNotified()                Sets the current record's "notified" value
 * @method AppUserRegisteredCompanies setAppUser()                 Sets the current record's "AppUser" value
 * @method AppUserRegisteredCompanies setRegisteredCompanies()     Sets the current record's "RegisteredCompanies" value
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAppUserRegisteredCompanies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('app_user_registered_companies');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('app_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('registered_companies_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('notified', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AppUser', array(
             'local' => 'app_user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('RegisteredCompanies', array(
             'local' => 'registered_companies_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}