<?php

/**
 * BaseProductsContractsIntermediation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $products_id
 * @property integer $contracts_intermediation_id
 * @property integer $registered_companies_id
 * @property string $percentage
 * @property Products $Products
 * @property ContractsIntermediation $ContractsIntermediation
 * @property RegisteredCompanies $RegisteredCompanies
 * 
 * @method integer                         getId()                          Returns the current record's "id" value
 * @method integer                         getProductsId()                  Returns the current record's "products_id" value
 * @method integer                         getContractsIntermediationId()   Returns the current record's "contracts_intermediation_id" value
 * @method integer                         getRegisteredCompaniesId()       Returns the current record's "registered_companies_id" value
 * @method string                          getPercentage()                  Returns the current record's "percentage" value
 * @method Products                        getProducts()                    Returns the current record's "Products" value
 * @method ContractsIntermediation         getContractsIntermediation()     Returns the current record's "ContractsIntermediation" value
 * @method RegisteredCompanies             getRegisteredCompanies()         Returns the current record's "RegisteredCompanies" value
 * @method ProductsContractsIntermediation setId()                          Sets the current record's "id" value
 * @method ProductsContractsIntermediation setProductsId()                  Sets the current record's "products_id" value
 * @method ProductsContractsIntermediation setContractsIntermediationId()   Sets the current record's "contracts_intermediation_id" value
 * @method ProductsContractsIntermediation setRegisteredCompaniesId()       Sets the current record's "registered_companies_id" value
 * @method ProductsContractsIntermediation setPercentage()                  Sets the current record's "percentage" value
 * @method ProductsContractsIntermediation setProducts()                    Sets the current record's "Products" value
 * @method ProductsContractsIntermediation setContractsIntermediation()     Sets the current record's "ContractsIntermediation" value
 * @method ProductsContractsIntermediation setRegisteredCompanies()         Sets the current record's "RegisteredCompanies" value
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductsContractsIntermediation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('products_contracts_intermediation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('products_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('contracts_intermediation_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('registered_companies_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('percentage', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Products', array(
             'local' => 'products_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('ContractsIntermediation', array(
             'local' => 'contracts_intermediation_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('RegisteredCompanies', array(
             'local' => 'registered_companies_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}