<?php

/**
 * BaseAppUserContractsIntermediation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $app_user_id
 * @property integer $contracts_intermediation_id
 * @property AppUser $AppUser
 * @property ContractsIntermediation $ContractsIntermediation
 * 
 * @method integer                        getId()                          Returns the current record's "id" value
 * @method integer                        getAppUserId()                   Returns the current record's "app_user_id" value
 * @method integer                        getContractsIntermediationId()   Returns the current record's "contracts_intermediation_id" value
 * @method AppUser                        getAppUser()                     Returns the current record's "AppUser" value
 * @method ContractsIntermediation        getContractsIntermediation()     Returns the current record's "ContractsIntermediation" value
 * @method AppUserContractsIntermediation setId()                          Sets the current record's "id" value
 * @method AppUserContractsIntermediation setAppUserId()                   Sets the current record's "app_user_id" value
 * @method AppUserContractsIntermediation setContractsIntermediationId()   Sets the current record's "contracts_intermediation_id" value
 * @method AppUserContractsIntermediation setAppUser()                     Sets the current record's "AppUser" value
 * @method AppUserContractsIntermediation setContractsIntermediation()     Sets the current record's "ContractsIntermediation" value
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAppUserContractsIntermediation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('app_user_contracts_intermediation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('app_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('contracts_intermediation_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AppUser', array(
             'local' => 'app_user_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('ContractsIntermediation', array(
             'local' => 'contracts_intermediation_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}