<?php

/**
 * BaseUserprojects
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $app_user_id
 * @property string $project_id
 * @property string $project_name
 * @property AppUser $AppUser
 * 
 * @method integer      getId()           Returns the current record's "id" value
 * @method integer      getAppUserId()    Returns the current record's "app_user_id" value
 * @method string       getProjectId()    Returns the current record's "project_id" value
 * @method string       getProjectName()  Returns the current record's "project_name" value
 * @method AppUser      getAppUser()      Returns the current record's "AppUser" value
 * @method Userprojects setId()           Sets the current record's "id" value
 * @method Userprojects setAppUserId()    Sets the current record's "app_user_id" value
 * @method Userprojects setProjectId()    Sets the current record's "project_id" value
 * @method Userprojects setProjectName()  Sets the current record's "project_name" value
 * @method Userprojects setAppUser()      Sets the current record's "AppUser" value
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserprojects extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('userprojects');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('app_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('project_id', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('project_name', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AppUser', array(
             'local' => 'app_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}