<?php

/**
 * BaseTypeOfInvestor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property Doctrine_Collection $TypeOfInvestor
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getCode()           Returns the current record's "code" value
 * @method Doctrine_Collection getTypeOfInvestor() Returns the current record's "TypeOfInvestor" collection
 * @method TypeOfInvestor      setId()             Sets the current record's "id" value
 * @method TypeOfInvestor      setName()           Sets the current record's "name" value
 * @method TypeOfInvestor      setCode()           Sets the current record's "code" value
 * @method TypeOfInvestor      setTypeOfInvestor() Sets the current record's "TypeOfInvestor" collection
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeOfInvestor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type_of_investor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('code', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Investor as TypeOfInvestor', array(
             'local' => 'id',
             'foreign' => 'type_of_investor_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}