<?php

/**
 * BaseTypeInformation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $TypeInformation
 * @property Doctrine_Collection $TempsDocuments
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getTypeInformation() Returns the current record's "TypeInformation" collection
 * @method Doctrine_Collection getTempsDocuments()  Returns the current record's "TempsDocuments" collection
 * @method TypeInformation     setId()              Sets the current record's "id" value
 * @method TypeInformation     setName()            Sets the current record's "name" value
 * @method TypeInformation     setTypeInformation() Sets the current record's "TypeInformation" collection
 * @method TypeInformation     setTempsDocuments()  Sets the current record's "TempsDocuments" collection
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeInformation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type_information');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DocumentsRegisteredCompanies as TypeInformation', array(
             'local' => 'id',
             'foreign' => 'type_information_id'));

        $this->hasMany('TempsDocuments', array(
             'local' => 'id',
             'foreign' => 'type_information_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}