<?php

/**
 * BaseRegisteredCompaniesContractsIntermediation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $registered_companies_id
 * @property integer $contracts_intermediation_id
 * @property string $type
 * @property RegisteredCompanies $RegisteredCompanies
 * @property ContractsIntermediation $ContractsIntermediation
 * 
 * @method integer                                    getId()                          Returns the current record's "id" value
 * @method integer                                    getRegisteredCompaniesId()       Returns the current record's "registered_companies_id" value
 * @method integer                                    getContractsIntermediationId()   Returns the current record's "contracts_intermediation_id" value
 * @method string                                     getType()                        Returns the current record's "type" value
 * @method RegisteredCompanies                        getRegisteredCompanies()         Returns the current record's "RegisteredCompanies" value
 * @method ContractsIntermediation                    getContractsIntermediation()     Returns the current record's "ContractsIntermediation" value
 * @method RegisteredCompaniesContractsIntermediation setId()                          Sets the current record's "id" value
 * @method RegisteredCompaniesContractsIntermediation setRegisteredCompaniesId()       Sets the current record's "registered_companies_id" value
 * @method RegisteredCompaniesContractsIntermediation setContractsIntermediationId()   Sets the current record's "contracts_intermediation_id" value
 * @method RegisteredCompaniesContractsIntermediation setType()                        Sets the current record's "type" value
 * @method RegisteredCompaniesContractsIntermediation setRegisteredCompanies()         Sets the current record's "RegisteredCompanies" value
 * @method RegisteredCompaniesContractsIntermediation setContractsIntermediation()     Sets the current record's "ContractsIntermediation" value
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegisteredCompaniesContractsIntermediation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registered_companies_contracts_intermediation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('registered_companies_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('contracts_intermediation_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RegisteredCompanies', array(
             'local' => 'registered_companies_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('ContractsIntermediation', array(
             'local' => 'contracts_intermediation_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}