<?php

/**
 * BaseContractsIntermediationComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $comments
 * @property integer $contracts_intermediation_id
 * @property integer $app_user_id
 * @property ContractsIntermediation $ContractsIntermediation
 * @property AppUser $AppUser
 * @property Doctrine_Collection $ContractsIntermediationComments
 * 
 * @method integer                         getId()                              Returns the current record's "id" value
 * @method text                            getComments()                        Returns the current record's "comments" value
 * @method integer                         getContractsIntermediationId()       Returns the current record's "contracts_intermediation_id" value
 * @method integer                         getAppUserId()                       Returns the current record's "app_user_id" value
 * @method ContractsIntermediation         getContractsIntermediation()         Returns the current record's "ContractsIntermediation" value
 * @method AppUser                         getAppUser()                         Returns the current record's "AppUser" value
 * @method Doctrine_Collection             getContractsIntermediationComments() Returns the current record's "ContractsIntermediationComments" collection
 * @method ContractsIntermediationComments setId()                              Sets the current record's "id" value
 * @method ContractsIntermediationComments setComments()                        Sets the current record's "comments" value
 * @method ContractsIntermediationComments setContractsIntermediationId()       Sets the current record's "contracts_intermediation_id" value
 * @method ContractsIntermediationComments setAppUserId()                       Sets the current record's "app_user_id" value
 * @method ContractsIntermediationComments setContractsIntermediation()         Sets the current record's "ContractsIntermediation" value
 * @method ContractsIntermediationComments setAppUser()                         Sets the current record's "AppUser" value
 * @method ContractsIntermediationComments setContractsIntermediationComments() Sets the current record's "ContractsIntermediationComments" collection
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContractsIntermediationComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contracts_intermediation_comments');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('comments', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('contracts_intermediation_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('app_user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ContractsIntermediation', array(
             'local' => 'contracts_intermediation_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('AppUser', array(
             'local' => 'app_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('DocumentsRegisteredCompanies as ContractsIntermediationComments', array(
             'local' => 'id',
             'foreign' => 'ci_comments_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}