<?php

/**
 * BaseContractsIntermediation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $year
 * @property integer $month
 * @property integer $day
 * @property string $customer
 * @property integer $app_user_id
 * @property text $observations
 * @property decimal $business_amount
 * @property decimal $intermediation
 * @property decimal $final_commission
 * @property text $comments
 * @property AppUser $AppUser
 * @property Doctrine_Collection $ContractsIntermediation
 * 
 * @method integer                 getId()                      Returns the current record's "id" value
 * @method integer                 getYear()                    Returns the current record's "year" value
 * @method integer                 getMonth()                   Returns the current record's "month" value
 * @method integer                 getDay()                     Returns the current record's "day" value
 * @method string                  getCustomer()                Returns the current record's "customer" value
 * @method integer                 getAppUserId()               Returns the current record's "app_user_id" value
 * @method text                    getObservations()            Returns the current record's "observations" value
 * @method decimal                 getBusinessAmount()          Returns the current record's "business_amount" value
 * @method decimal                 getIntermediation()          Returns the current record's "intermediation" value
 * @method decimal                 getFinalCommission()         Returns the current record's "final_commission" value
 * @method text                    getComments()                Returns the current record's "comments" value
 * @method AppUser                 getAppUser()                 Returns the current record's "AppUser" value
 * @method Doctrine_Collection     getContractsIntermediation() Returns the current record's "ContractsIntermediation" collection
 * @method ContractsIntermediation setId()                      Sets the current record's "id" value
 * @method ContractsIntermediation setYear()                    Sets the current record's "year" value
 * @method ContractsIntermediation setMonth()                   Sets the current record's "month" value
 * @method ContractsIntermediation setDay()                     Sets the current record's "day" value
 * @method ContractsIntermediation setCustomer()                Sets the current record's "customer" value
 * @method ContractsIntermediation setAppUserId()               Sets the current record's "app_user_id" value
 * @method ContractsIntermediation setObservations()            Sets the current record's "observations" value
 * @method ContractsIntermediation setBusinessAmount()          Sets the current record's "business_amount" value
 * @method ContractsIntermediation setIntermediation()          Sets the current record's "intermediation" value
 * @method ContractsIntermediation setFinalCommission()         Sets the current record's "final_commission" value
 * @method ContractsIntermediation setComments()                Sets the current record's "comments" value
 * @method ContractsIntermediation setAppUser()                 Sets the current record's "AppUser" value
 * @method ContractsIntermediation setContractsIntermediation() Sets the current record's "ContractsIntermediation" collection
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContractsIntermediation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contracts_intermediation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('year', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('month', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('day', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('customer', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('app_user_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('observations', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('business_amount', 'decimal', 9, array(
             'type' => 'decimal',
             'length' => 9,
             'scale' => '2',
             ));
        $this->hasColumn('intermediation', 'decimal', 9, array(
             'type' => 'decimal',
             'length' => 9,
             'scale' => '2',
             ));
        $this->hasColumn('final_commission', 'decimal', 9, array(
             'type' => 'decimal',
             'length' => 9,
             'scale' => '2',
             ));
        $this->hasColumn('comments', 'text', null, array(
             'type' => 'text',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AppUser', array(
             'local' => 'app_user_id',
             'foreign' => 'id'));

        $this->hasMany('Notifications as ContractsIntermediation', array(
             'local' => 'id',
             'foreign' => 'contracts_intermediation_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}