<?php

/**
 * BaseProductRegisteredCompanies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $products_id
 * @property integer $registered_companies_id
 * @property Products $Products
 * @property RegisteredCompanies $RegisteredCompanies
 * 
 * @method integer                    getId()                      Returns the current record's "id" value
 * @method integer                    getProductsId()              Returns the current record's "products_id" value
 * @method integer                    getRegisteredCompaniesId()   Returns the current record's "registered_companies_id" value
 * @method Products                   getProducts()                Returns the current record's "Products" value
 * @method RegisteredCompanies        getRegisteredCompanies()     Returns the current record's "RegisteredCompanies" value
 * @method ProductRegisteredCompanies setId()                      Sets the current record's "id" value
 * @method ProductRegisteredCompanies setProductsId()              Sets the current record's "products_id" value
 * @method ProductRegisteredCompanies setRegisteredCompaniesId()   Sets the current record's "registered_companies_id" value
 * @method ProductRegisteredCompanies setProducts()                Sets the current record's "Products" value
 * @method ProductRegisteredCompanies setRegisteredCompanies()     Sets the current record's "RegisteredCompanies" value
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductRegisteredCompanies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_registered_companies');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('products_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('registered_companies_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Products', array(
             'local' => 'products_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('RegisteredCompanies', array(
             'local' => 'registered_companies_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}