<?php

/**
 * BaseTypeCalendar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $TypeCalendar
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method Doctrine_Collection getTypeCalendar() Returns the current record's "TypeCalendar" collection
 * @method TypeCalendar        setId()           Sets the current record's "id" value
 * @method TypeCalendar        setName()         Sets the current record's "name" value
 * @method TypeCalendar        setTypeCalendar() Sets the current record's "TypeCalendar" collection
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTypeCalendar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('type_calendar');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Calendar as TypeCalendar', array(
             'local' => 'id',
             'foreign' => 'type_calendar_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}