<?php

/**
 * AppUserRegisteredCompaniesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AppUserRegisteredCompaniesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AppUserRegisteredCompaniesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AppUserRegisteredCompanies');
    }
    
    /**
     * Get array of all bedrooms for select tag
     * @param string $id 
     * @return array
     */
    public function getAllForSelectContactAssociated($id)
    {
           $arr_options = array();
           
           $q = Doctrine_Query::create()
                   ->select('ar.*, au.id AS id, au.name AS name, au.last_name AS last_name, ur.name AS rol')
                   ->from('AppUserRegisteredCompanies ar')
                   ->leftJoin('ar.AppUser au')
                   ->leftJoin('au.UserRole ur')
                   ->where('ar.registered_companies_id = ?', $id)
                   ->orderBy('id');
           
           $d = $q->fetchArray();

           foreach ($d as $value) {
                   $arr_options[$value['id']] = $value['name'].' '.$value['last_name'].' ('.$value['rol'].')';
           }
           return $arr_options;
    }
}