<?php

/**
 * BillingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BillingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BillingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Billing');
    }
    
    /**
     * Get pager for list of calendar
     *
     * @param integer $page
     * @param integer $per_page
     * @param string $filter
     * @param string $order
     * @return doctrine pager
     */
    public function getPager($page, $per_page, $filter, $order)
    {
           $oPager = new sfDoctrinePager('Billing', $per_page);
           $oPager->getQuery()
                ->from('Billing')
                ->where($filter)
                ->orderBy($order);
           $oPager->setPage($page);
           $oPager->init();

           return $oPager;
    } 
}