<?php

/**
 * ContractsIntermediationCommentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContractsIntermediationCommentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContractsIntermediationCommentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContractsIntermediationComments');
    }
}