<?php

/**
 * ContractsIntermediation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ContractsIntermediation extends BaseContractsIntermediation
{
  /**
   * Get array for select
   * @return array
   */
  public static function getArrayForSelect()
  {
    $object = ContractsIntermediationTable::getInstance()->getContractOrdeyBy();
    $array = array(''=>'-- Seleccionar --');
    
    foreach ($object AS $v)
    {
      $company = $v->getRegisteredCompanies()?$v->getRegisteredCompanies()->getName().' (Participada)':$v->getCompanyName();  
      $array[$v->getId()] = $v->getCustomerName().' - '.$company;
    }
    return $array;
  }
}
