<?php

/**
 * ContractsIntermediationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContractsIntermediationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContractsIntermediationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ContractsIntermediation');
    }
    
    /**
     * Get pager for list of contracts
     *
     * @param integer $page
     * @param integer $per_page
     * @param string $filter
     * @param string $order
     * @return doctrine pager
     */
    public function getPager($page, $per_page, $filter, $order)
    {
        $oPager = new sfDoctrinePager('ContractsIntermediation', $per_page);
        $oPager->getQuery()
            ->from('ContractsIntermediation')
            ->where($filter)
            ->orderBy($order);
        $oPager->setPage($page);
        $oPager->init();

        return $oPager;
     }
}