<?php

/**
 * DocumentsRegisteredCompaniesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentsRegisteredCompaniesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentsRegisteredCompaniesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentsRegisteredCompanies');
    }
    
    /**
     * get documents by company
     * @param int $id_company
     * @return object
     */
    public function getDocumentsByCompany($id_company)
    {
        $q = $this->createQuery()
             ->where('information_id IS NULL AND registered_companies_id = '.$id_company)
             ->orderBy('id DESC');
        
        return $q->execute();
    }
    
    /**
     * get documents by company and type
     * @param int $id_company
     * @param array $type 
     * @return object
     */
    public function getDocumentsByCompanyAndType($id_company, $type)
    {
        $q = $this->createQuery()
             ->where('registered_companies_id = '.$id_company)
             ->whereIn('type_information_id', $type)
             ->andWhere('entrepreneur_id IS NULL AND calendar_id IS NULL')   
             ->orderBy('id DESC');
        
        return $q->execute();
    }
    
    /**
     * get document by contrat
     * @param int $id_contrat
     * @return object
     */
    public function getDocumentByContrat($id_contrat, $no_comment = NULL)
    {
        $q = $this->createQuery()
             ->where('contracts_intermediation_id = '.$id_contrat)  
             ->orderBy('id DESC');
        
        if($no_comment)
        {
            $q->andWhere('ci_comments_id Is NULL');
        }    
        
        return $q->execute();
    }        
}