<?php

/**
 * DocumentsRegisteredCompaniesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentsRegisteredCompaniesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentsRegisteredCompaniesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentsRegisteredCompanies');
    }
    
    /**
     * get documents by company
     * @param int $id_company
     * @return object
     */
    public function getDocumentsByCompany($id_company)
    {
        $q = $this->createQuery()
             ->where('information_id IS NULL AND registered_companies_id = '.$id_company)
             ->orderBy('id DESC');
        
        return $q->execute();
    }      
}