<?php

/**
 * InformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Information');
    }
    
    /**
     * Get pager for list of users
     *
     * @param integer $page
     * @param integer $per_page
     * @param string $filter
     * @param string $order
     * @return doctrine pager
     */
    public function getPager($page, $per_page, $filter, $order)
    {
        $oPager = new sfDoctrinePager('Information', $per_page);
        $oPager->getQuery()
            ->from('Information')
            ->where($filter)
            ->orderBy($order);
        $oPager->setPage($page);
        $oPager->init();

        return $oPager;
     }
     
     /**
      * get information
      * @return object
      */
     public function getInformation()
     {
         $q = $this->createQuery()
              ->limit(10)
              ->orderBy('id DESC');
         
         return $q->execute();
     }        
}