<?php

/**
 * Notifications
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    liprandi
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Notifications extends BaseNotifications
{
    
    public static function setNewNotification($type, $subject, $company_id='', $apps_user_id = '', $informatio_id = '', $contracts_intermediation_id = '')
    {
       $notification = new Notifications();
       $notification->setType($type);
       $notification->setSubject($subject);
       
       if($company_id!='')
       {
           $notification->setRegisteredCompaniesId($company_id);    
       }
       
       if($apps_user_id != '')
       {
           $notification->setAppUserId($apps_user_id);
       }    
       
       if($informatio_id != '')
       {
           $notification->setInformationId($informatio_id);
       }
       
       if($contracts_intermediation_id != '')
       {
           $notification->setContractsIntermediationId($contracts_intermediation_id);
       }
       
       $notification->save();
       
       return true;
       
    }        
}
