<?php

/**
 * ProductsContractsIntermediationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductsContractsIntermediationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductsContractsIntermediationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductsContractsIntermediation');
    }
}