<?php

/**
 * RegisteredCompaniesContractsIntermediation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    egauss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RegisteredCompaniesContractsIntermediation extends BaseRegisteredCompaniesContractsIntermediation
{
    /**
     * setCompanyInContract
     * @param int $contract
     * @param array $company_post
     * @param string $type
     * @param int $id
     */
    public static function setCompanyInContract($contract, $company_post, $type, $id = NULL)
    {
        if ($id)
        {
          $d_company = RegisteredCompaniesContractsIntermediationTable::getInstance()->findByContractsIntermediationIdAndType($id, $type);  
          foreach ($d_company as $d){
            $array_company[$d->getRegisteredCompaniesId()] = $d->getRegisteredCompaniesId();           
          }

        }
        $array_company_active = '(0,';
        foreach ($company_post AS $k => $v)
        {
            if($id != '')
            {
                if(empty($array_company[$v])){
                    self::setNewCompanyInContract($v, $contract, $type);
                }

            }
            else
            {
                self::setNewCompanyInContract($v, $contract, $type);
            }    

            $array_company_active .= $v.',';
        }
        $string_company = substr($array_company_active, 0, -1).')';

        if($string_company && $id){
          $d_company_not_in_contract  = RegisteredCompaniesContractsIntermediationTable::getInstance()->deleteCompanyNotInContract($string_company, $contract, $type);
        }
    }  
    
    /**
     * setNewCompanyInContract
     * @param int $contarct
     * @param int $company
     * @param string $type
     */
    public function setNewCompanyInContract($company, $contarct, $type)
    {
        $compnay = new RegisteredCompaniesContractsIntermediation();
        $compnay->setContractsIntermediationId($contarct);
        $compnay->setRegisteredCompaniesId($company);
        $compnay->setType($type);
        $compnay->save();
    }        
}
