<?php

/**
 * RegisteredCompaniesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegisteredCompaniesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegisteredCompaniesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegisteredCompanies');
    }
    
    /**
     * Get pager for list of users
     *
     * @param integer $page
     * @param integer $per_page
     * @param string $filter
     * @param string $order
     * @return doctrine pager
     */
    public function getPager($page, $per_page, $filter, $order)
    {
        $oPager = new sfDoctrinePager('RegisteredCompanies', $per_page);
        $oPager->getQuery()
            ->from('RegisteredCompanies')
            ->where($filter)
            ->orderBy($order);
        $oPager->setPage($page);
        $oPager->init();

        return $oPager;
     }
     
   /**
    * Upload logo process
    *
    * @param array $file
    * @param mixed $recorded
    * @param boolean $reset
    */ 
    public function uploadLogo($file, $recorded, $reset = false)
    {
          $destination = ServiceFileHandler::getUploadFolder('company');

          if ($file['size'] > 0)
          {
                  $f_extension = strtolower(strrchr($file['name'], '.'));
                          $upload_file = date('Y').'/'.uniqid('').$f_extension;

                          if (move_uploaded_file($file['tmp_name'], $destination.$upload_file)) {
                                  if ($recorded->getLogo()) {
                                          @unlink($destination.$recorded->getLogo());
                                          @unlink($destination.ServiceFileHandler::getThumbImage($recorded->getLogo()));
                                  }
                                  @chmod($destination.$upload_file, 0777);
                                  $recorded->setLogo($upload_file);

                                  ## Create thumbnail
                                  $oResize = new ResizeImage();
                                  $aThumbs = array(ServiceFileHandler::getThumbImage($upload_file) => array('w'=>20, 'h'=>20), $upload_file => array('w'=>150, 'h'=>150));
                                  $oResize->setMultiple($upload_file, $aThumbs, $destination, 0, 0, $f_extension, array('metodo' => 'full'));
                          }
          } 
          elseif ($reset && $recorded->getLogo())
          {
                  @unlink($destination.$recorded->getLogo());
                  @unlink($destination.ServiceFileHandler::getThumbImage($recorded->getLogo()));

                  $recorded->setLogo(NULL);
          }
          $recorded->save();
    }
    
    
    /**
     * get affiliated
     * @return object
     */
    public function getAffiliated()
    {
        $q = $this->createQuery()
             ->where('id >1 AND type_companies_id = 1');
        
        return $q->execute();
    }        
}