<?php

/**
 * RegisteredCompaniesContractsIntermediationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegisteredCompaniesContractsIntermediationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegisteredCompaniesContractsIntermediationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegisteredCompaniesContractsIntermediation');
    }
    
    /**
     * Get array of all for select tag
     * @param string $id 
     * @return array
     */
    public function getAllForSelectCompanyAssociated($id, $type)
    {
           $arr_options = array();
           
           $q = Doctrine_Query::create()
                   ->select('rcc.*, rc.id AS id, rc.name AS name, tc.id AS tc_id, tc.name AS type')
                   ->from('RegisteredCompaniesContractsIntermediation rcc')
                   ->leftJoin('rcc.RegisteredCompanies rc')
                   ->leftJoin('rc.TypeCompanies tc')
                   ->where('rcc.contracts_intermediation_id = ?', $id)
                   ->andWhere('rcc.type = ?', $type)
                   ->orderBy('id');
           
           $d = $q->fetchArray();

           foreach ($d as $value) {
                   $type = $value['tc_id']==1?' ('.$value['type'].')':'';
                   $arr_options[$value['id']] = $value['name'].$type;
           }
           return $arr_options;
    }
    
    /**
     * delete company not in contract
     * @param string $array_company
     * @param int $contract_id
     * @param string $type
     * @return delete
     */
    public function deleteCompanyNotInContract($array_company, $contract_id, $type)
    {
        $q = $this->createQuery()
             ->where('contracts_intermediation_id = ?', $contract_id)
             ->andWhere('type = ?', $type)   
             ->andWhere('registered_companies_id NOT IN '.$array_company )
             ->delete();
        
        
        return $q->execute();
    } 
    
    /**
     * Get array of all for select tag
     * @param string $id 
     * @return array
     */
    public function getAllCompanyAssociated($id, $type = '')
    {
           
           $q = Doctrine_Query::create()
                   ->select('rcc.*, rc.id AS id, rc.name AS name, tc.id AS tc_id, tc.name AS type')
                   ->from('RegisteredCompaniesContractsIntermediation rcc')
                   ->leftJoin('rcc.RegisteredCompanies rc')
                   ->leftJoin('rc.TypeCompanies tc')
                   ->where('rcc.contracts_intermediation_id = ?', $id)
                   ->andWhere('rcc.type = ?', $type)
                   ->orderBy('id');
           
           return $q->execute();
    }
    
    /**
     * getAllContractByCompany
     * @param string $array_company 
     * @return array
     */
    public function getAllContractByCompany($array_company)
    {
        $q = $this->createQuery()
                ->where('registered_companies_id  IN '.$array_company )
                ->orderBy('id');

        return $q->execute();
    }
}