<?php

/**
 * TempsDocumentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TempsDocumentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TempsDocumentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TempsDocuments');
    }
}