<?php

/**
 * TicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TicTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tic');
    }
}