<?php

/**
 * TypeInformationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeInformationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeInformationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeInformation');
    }
}