<?php

/**
 * TypeOfInvestorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeOfInvestorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeOfInvestorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeOfInvestor');
    }
}