<?php

/**
 * TypeCompaniesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypeCompaniesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypeCompaniesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypeCompanies');
    }
}