<?php

/**
 * UserprojectsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserprojectsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserprojectsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Userprojects');
    }
}