
all:
  recaptcha_public_key: 6LdmU70SAAAAAMYSeNgt_7msy3RNKe9gp0_qM2L9
  recaptcha_private_key: 6LdmU70SAAAAAHprwsVhmdjpvoKhq-ZW9qgvtall

  project_reference_name: eGauss Business Holding I+T
  no_replay_email_account: noreply@emailbase.com.ar
  
  outgoing_smtp_server: smtp.gmail.com
  outgoing_smtp_port: 465
  outgoing_smtp_account: icox.automatic.service@gmail.com
  outgoing_smtp_password: la-virginia
  
  # basecamp config
  bcamp_name: eGauss
  bcamp_contact: basecamp@egauss.com
  bcamp_account: 2498346
  bcamp_username: miguelmate@egauss.com
  bcamp_password: Piruleta1911
