################################################################### entrepreneur

# entrepreneur-delete-document rules
entrepreneur-delete-document:
  url:   /entrepreneur-delete-document
  param: { module: entrepreneur, action: deleteDocument }

# entrepreneur-get-components-documents rules
entrepreneur-get-components-documents:
  url:   /entrepreneur-get-components-documents
  param: { module: entrepreneur, action: getComponentsDocuments }
  
# entrepreneur-register-document rules
entrepreneur-register-document:
  url:   /entrepreneur-register-document
  param: { module: entrepreneur, action: registerDocument }

# entrepreneur-delete-video rules
entrepreneur-delete-video:
  url:   /entrepreneur-delete-video
  param: { module: entrepreneur, action: deleteVideo }

# entrepreneur-get-components-videos rules
entrepreneur-get-components-videos:
  url:   /entrepreneur-get-components-videos
  param: { module: entrepreneur, action: getComponentsVideos }
  
# entrepreneur-register-video rules
entrepreneur-register-video:
  url:   /entrepreneur-register-video
  param: { module: entrepreneur, action: registerVideo }
  
# entrepreneur-delete rules
entrepreneur-delete:
  url:   /entrepreneur-delete/:id
  param: { module: entrepreneur, action: delete }

# entrepreneur-edit rules
entrepreneur-edit:
  url:   /entrepreneur-edit/:id
  param: { module: entrepreneur, action: edit }

# entrepreneur-register rules
entrepreneur-register:
  url:   /entrepreneur-register
  param: { module: entrepreneur, action: register }
  
# entrepreneur-show rules
entrepreneur-show:
  url:   /entrepreneur-show/:id
  param: { module: entrepreneur, action: show }
  
# entrepreneur rules
entrepreneur:
  url:   /entrepreneur
  param: { module: entrepreneur, action: index }

################################################################### basecamp

# project-list rules
project-list:
  url:   /project-list
  param: { module: basecamp, action: index }

# task-list rules
task-list:
  url:   /task-list/:id/:project/:account
  param: { module: basecamp, action: resumen }

################################################################### inversores

# investor-delete rules
investor-delete:
  url:   /investor-delete/:id
  param: { module: investor, action: delete }

# investor-edit rules
investor-edit:
  url:   /investor-edit/:id
  param: { module: investor, action: edit }

# investor-register rules
investor-register:
  url:   /investor-register
  param: { module: investor, action: register }
  
# investor-show rules
investor-show:
  url:   /investor-show/:id
  param: { module: investor, action: show }
  
# investors rules
investors:
  url:   /investors
  param: { module: investor, action: index }

# investors export to excel
investor-excel:
  url:   /investor-excel
  param: { module: investor, action: excel }

################################################################### contracts

# contracts-delete-document rules
contracts-delete-document:
  url:   /contracts-delete-document
  param: { module: contracts, action: deleteDocument }

# contracts-get-components-documents rules
contracts-get-components-documents:
  url:   /contracts-get-components-documents
  param: { module: contracts, action: getComponentsDocuments }
  
# contracts-register-document rules
contracts-register-document:
  url:   /contractsanalyzed-register-document
  param: { module: contracts, action: registerDocument }

# delete-reunion-by-contract
delete-reunion-by-contract:
  url:   /delete-reunion-by-contract
  param: { module: contracts, action: deleteReunionByContract }
  
# contracts-by-month-year
contracts-by-month-year:
  url:   /contracts-by-month-year
  param: { module: contracts, action: contractsByMonthYear }
  
# contracts-delete rules
contracts-delete:
  url:   /contracts-delete/:id
  param: { module: contracts, action: delete }

# contracts-edit rules
contracts-edit:
  url:   /contracts-edit/:id
  param: { module: contracts, action: edit }

# contracts-register rules
contracts-register:
  url:   /contracts-register
  param: { module: contracts, action: register }
  
# contracts-show rules
contracts-show:
  url:   /contracts-show/:id
  param: { module: contracts, action: show }
  
# contracts rules
contracts:
  url:   /contracts
  param: { module: contracts, action: index }
  
################################################################### billing

# billing-by-month-year
billing-by-month-year:
  url:   /billing-by-month-year
  param: { module: billing, action: billingByMonthYear }
  
# billing-delete rules
billing-delete:
  url:   /billing-delete/:id
  param: { module: billing, action: delete }

# billing-edit rules
billing-edit:
  url:   /billing-edit/:id
  param: { module: billing, action: edit }

# billing-register rules
billing-register:
  url:   /billing-register
  param: { module: billing, action: register }
  
# billing-show rules
billing-show:
  url:   /billing-show/:id
  param: { module: billing, action: show }
  
# billing rules
billing:
  url:   /billing
  param: { module: billing, action: index }
  
################################################################### shareholders

# shareholders-delete-document rules
shareholders-delete-document:
  url:   /shareholders-delete-document
  param: { module: shareholders, action: deleteDocument }

# shareholders-get-components-documents rules
shareholders-get-components-documents:
  url:   /shareholders-get-components-documents
  param: { module: shareholders, action: getComponentsDocuments }
  
# shareholders-register-document rules
shareholders-register-document:
  url:   /shareholders-register-document
  param: { module: shareholders, action: registerDocument }

# shareholders-delete rules
shareholders-delete:
  url:   /shareholders-delete/:id
  param: { module: shareholders, action: delete }

# shareholders-edit rules
shareholders-edit:
  url:   /shareholders-edit/:id
  param: { module: shareholders, action: edit }

# shareholders-register rules
shareholders-register:
  url:   /shareholders-register
  param: { module: shareholders, action: register }
  
# shareholders-show rules
shareholders-show:
  url:   /shareholders-show/:id
  param: { module: shareholders, action: show }
  
# shareholders rules
shareholders:
  url:   /shareholders
  param: { module: shareholders, action: index }


#################################################################### information

# information-delete-document rules
information-delete-document:
  url:   /information-delete-document
  param: { module: information, action: deleteDocument }

# information-get-components-documents rules
information-get-components-documents:
  url:   /information-get-components-documents
  param: { module: information, action: getComponentsDocuments }
  
# information-register-document rules
information-register-document:
  url:   /information-register-document
  param: { module: information, action: registerDocument }

# information-delete-video rules
information-delete-video:
  url:   /information-delete-video
  param: { module: information, action: deleteVideo }

# information-get-components-videos rules
information-get-components-videos:
  url:   /information-get-components-videos
  param: { module: information, action: getComponentsVideos }
  
# information-register-video rules
information-register-video:
  url:   /information-register-video
  param: { module: information, action: registerVideo }
  
# information-delete rules
information-delete:
  url:   /information-delete/:id
  param: { module: information, action: delete }

# information-edit rules
information-edit:
  url:   /information-edit/:id
  param: { module: information, action: edit }

# information-register rules
information-register:
  url:   /information-register
  param: { module: information, action: register }
  
# information-show rules
information-show:
  url:   /information-show/:id
  param: { module: information, action: show }
  
# information rules
information:
  url:   /information
  param: { module: information, action: index }


#################################################################### analyzed

# analyzed-delete-document rules
analyzed-delete-document:
  url:   /analyzed-delete-document
  param: { module: analyzed, action: deleteDocument }

# analyzed-get-components-documents rules
analyzed-get-components-documents:
  url:   /analyzed-get-components-documents
  param: { module: analyzed, action: getComponentsDocuments }
  
# analyzed-register-document rules
analyzed-register-document:
  url:   /analyzed-register-document
  param: { module: analyzed, action: registerDocument }

# analyzed-delete-video rules
analyzed-delete-video:
  url:   /analyzed-delete-video
  param: { module: analyzed, action: deleteVideo }

# analyzed-get-components-videos rules
analyzed-get-components-videos:
  url:   /analyzed-get-components-videos
  param: { module: analyzed, action: getComponentsVideos }
  
# analyzed-register-video rules
analyzed-register-video:
  url:   /analyzed-register-video
  param: { module: analyzed, action: registerVideo }
  
# analyzed-delete rules
analyzed-delete:
  url:   /analyzed-delete/:id
  param: { module: analyzed, action: delete }

# analyzed-edit rules
analyzed-edit:
  url:   /analyzed-edit/:id
  param: { module: analyzed, action: edit }

# analyzed-register rules
analyzed-register:
  url:   /analyzed-register
  param: { module: analyzed, action: register }
  
# analyzed-show rules
analyzed-show:
  url:   /analyzed-show/:id
  param: { module: analyzed, action: show }
  
# analyzed rules
analyzed:
  url:   /analyzed
  param: { module: analyzed, action: index }


#################################################################### affiliated

# affiliated-delete-document rules
affiliated-delete-document:
  url:   /affiliated-delete-document
  param: { module: affiliated, action: deleteDocument }

# affiliated-get-components-documents rules
affiliated-get-components-documents:
  url:   /affiliated-get-components-documents
  param: { module: affiliated, action: getComponentsDocuments }
  
# affiliated-register-document rules
affiliated-register-document:
  url:   /affiliated-register-document
  param: { module: affiliated, action: registerDocument }

# affiliated-delete-video rules
affiliated-delete-video:
  url:   /affiliated-delete-video
  param: { module: affiliated, action: deleteVideo }

# affiliated-get-components-videos rules
affiliated-get-components-videos:
  url:   /affiliated-get-components-videos
  param: { module: affiliated, action: getComponentsVideos }
  
# affiliated-register-video rules
affiliated-register-video:
  url:   /affiliated-register-video
  param: { module: affiliated, action: registerVideo }
  
# affiliated-delete rules
affiliated-delete:
  url:   /affiliated-delete/:id
  param: { module: affiliated, action: delete }

# affiliated-edit rules
affiliated-edit:
  url:   /affiliated-edit/:id
  param: { module: affiliated, action: edit }

# affiliated-register rules
affiliated-register:
  url:   /affiliated-register
  param: { module: affiliated, action: register }
  
# affiliated-show rules
affiliated-show:
  url:   /affiliated-show/:id
  param: { module: affiliated, action: show }
  
# affiliated rules
affiliated:
  url:   /affiliated
  param: { module: affiliated, action: index }
  
#################################################################### calendar

# calendar-delete rules
calendar-delete:
  url:   /calendar-delete/:id/:sch_year/:sch_month/:sch_day
  param: { module: calendar, action: delete }

# calendar-edit rules
calendar-edit:
  url:   /calendar-edit/:id/:sch_year/:sch_month/:sch_day
  param: { module: calendar, action: edit }

# calendar-register rules
calendar-register:
  url:   /calendar-register/:sch_year/:sch_month/:sch_day
  param: { module: calendar, action: register }
  
# calendar-show rules
calendar-show:
  url:   /calendar-show/:id/:sch_year/:sch_month/:sch_day
  param: { module: calendar, action: show }

# calendar rules
calendar:
  url:   /calendar/:sch_year/:sch_month/:sch_day
  param: { module: calendar, action: index }

# calendar-get-date rules
calendar-get-date:
  url:   /calendar-get-date
  param: { module: calendar, action: getDate }

# calendar listado
calendar_lista:
  url:   /calendar
  param: { module: calendar, action: index }

#################################################################### user

# user-view rules
user-view:
  url:   /user-view/:id
  param: { module: user, action: viewUser }

# user-delete rules
user-delete:
  url:   /user-delete/:id
  param: { module: user, action: delete }

# user-edit rules
user-edit:
  url:   /user-edit/:id
  param: { module: user, action: edit }

# user-register rules
user-register:
  url:   /user-register
  param: { module: user, action: register }
  
# user-show rules
user-show:
  url:   /user-show/:id
  param: { module: user, action: show }
  
# user rules
user:
  url:   /users
  param: { module: user, action: index }

# my-profile rules
my-profile:
  url:   /user-edit/:id/:profile
  param: { module: user, action: edit }

# logout rules
logout:
  url:   /logout
  param: { module: home, action: logout }


# default rules
homepage:
  url:   /
  param: { module: home, action: index }

#google_drive
google_drive:
  url: /google-drive
  param: { module: home, action: googleDrive }

# show-document rules
show-document:
  url:   /show-document/:id
  param: { module: home, action: showDocument }
  
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
